apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: minio-operator
    meta.helm.sh/release-namespace: minio-operator
  creationTimestamp: "2023-11-03T16:54:33Z"
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v5.0.10
    helm.sh/chart: operator-5.0.10
  name: console
  namespace: minio-operator
  resourceVersion: "6859"
  uid: 68aa5043-5ed9-4a14-9b7f-9ef7f761221d
spec:
  clusterIP: 10.0.159.177
  clusterIPs:
    - 10.0.159.177
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30080
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
